### ISSUE TITLE
fix dawgie.db.shelf.Interface

### ISSUE THREAD

**Issue by al-niessner** [al-niessner/DAWGIE#102]
Remove `as_dict()` and implement `__iter__()`. It should be sufficient to have it use the `__span.items()`.

**Comment by jpl-jengelke** [comment]
2020-02-04 18:46:04,341 :: dawgie.pl.worker :: ERROR :: Job "data_reduction.ingest" failed to execute successfully for run id 5 and target "None"
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 125, in execute
    m.jobid, m.runid, m.target, m.timing)
  File "/usr/local/lib/python3.6/dist-packages/dawgie/pl/worker.py", line 85, in run
    task.do (goto=jobid.split('.')[1])
  File "/usr/local/lib/python3.6/dist-packages/dawgie/__init__.py", line 365, in do
    self.measure (step.run, args=(aspect,), ds=aspect.ds())
  File "/usr/local/lib/python3.6/dist-packages/dawgie/__init__.py", line 183, in measure
    value = func (*args)
  File "/proj/survey-ws/src/ets/data_reduction/ingest/__init__.py", line 44, in run
    sv = aspects_dict['data_reduction.scrape_aavso.SVReduction']['__all__']
KeyError: 'data_reduction.scrape_aavso.SVReduction'

**Comment by jpl-jengelke** [comment]
This is what the aspect_dict looks like on a Postgres machine: 

ops_worker_3        | ('__all__', {'data_reduction.scrape_aavso.SVReduction': {'scrape_aavso_date_start': 2020-02-05 02:44:49.529677+00:00, 'scrape_aavso_date_end': 2020-02-05 02:46:00.708283+00:00, 'scrape_aavso_files': ['00200_cdec_wasp-12b_20160106__000442.zip', '00165_cdec_wasp-12b_20160106__022250.zip', '00170_cdec_wasp-12b_20160106__022250.zip', '00166_cdec_wasp-12b_20160108__022250.zip', '00216_fmaa_tres-3-b_20170502__093414.zip', '00209_fmaa_wasp-52-b_20171012__034435.zip', '00206_fmaa_wasp-52b_20171026__034132.zip', '00173_bsec_tres-3b_20171113__001532.zip', '00233_zrta_hat-p-32-b_20171220__050845.zip', '00171_ldia_qatar-1b_20181213__210747.zip', '00242_fmaa_hat-p-32-b_20181214__062005.zip', '00227_cgia_kelt-7b_20190115__191728.zip', '00174_ldia_hat-p-32-b_20190203__205603.zip', '00175_ldia_hat-p-36-b_20190223__223628.zip', '00178_lpac_kelt-3b_20190330__064144.zip', '00177_lpac_kps-1b_20190401__065610.zip', '00179_mhsb_hat-p-36_20190402__022548.zip', '00176_lpac_wasp-104b_20190402__071358.zip', '00187_lpac_k2-137b_20190411__061816.zip', '00180_mhsb_wasp-43b_20190418__023108.zip', '00181_akv_hat-p-36b_20190419__073456.zip', '00183_lpac_k2-137b_20190423__065125.zip', '00182_lpac_xo-1b_20190424__092856.zip', '00184_lpac_xo-6b_20190504__061718.zip', '00185_rdja_wasp-19b_20190517__100613.zip', '00246_dks_tres-3_20190518__055203.zip', '00186_lpac_wts-2b_20190518__081442.zip', '00189_rdja_hats-24b_20190527__125904.zip', '00188_lpac_kepler-1086b_20190530__075809.zip', '00193_mxi_qatar-1b_20190531__211012.zip', '00194_pcc_qatar-1b_20190531__223420.zip', '00190_lpac_kepler-446c_20190609__090103.zip', '00191_lpac_kepler-718b_20190611__073256.zip', '00192_pcc_wasp-48b_20190626__231029.zip', '00197_mxi_tres-3b_20190629__001259.zip', '00195_pcc_corot-2b_20190701__230856.zip', '00196_pcc_kelt-16_20190713__231822.zip', '00198_pcc_tres-2b_20190716__231356.zip', '00199_pcc_tres3b_20190719__222336.zip', '00201_pcc_hat-p-41b_20190720__231831.zip', '00207_pcc_wasp-92b_20190721__230837.zip', '00208_lpac_wasp-67b_20190808__065936.zip', '00214_mnic_xo-6-b_20190812__215454.zip', '00217_mnic_qatar-4-b_20190821__214704.zip', '00221_fmaa_wasp-10-b_20190826__050131.zip', '00218_mnic_tres-5-b_20190827__231322.zip', '00220_mnic_kepler-412-b_20190828__212333.zip', '00234_lpac_wts2b_20190901__064656.zip', '00222_pcc_wasp-3b_20190904__220652.zip', '00223_mnic_tres-2-b_20190906__204859.zip', '00224_mnic_tres-3-b_20190908__204627.zip', '00226_lpac_hd-189733-b_20190912__061611.zip', '00240_fmaa_hat-p-32-b_20190913__074756.zip', '00225_mnic_wasp-10-b_20190916__202510.zip', '00228_fmaa_hat-p-32-b_20190928__084711.zip', '00229_fmaa_wasp-10-b_20191002__073501.zip', '00230_mnic_tres-5-b_20191021__193302.zip', '00238_fmaa_hat-p-32-b_20191024__040421.zip', '00235_mnic_k2-30-b_20191105__210806.zip', '00245_dks_wasp-12_20191129__075051.zip', '00244_kgab_hat-p-19_20191202__041602.zip', '00247_fmaa_wasp-77-a-b_20200107__051300.zip', '00248_kadb_wasp-34-b_20200126__014328.zip'], 'ingest_headers': [], 'ingest_data': [], 'STATUS': [False, True]}})

**Comment by jpl-jengelke** [comment]
This is what the aspect_dict looks like on a shelf machine:

dev_worker_1    | ('data_reduction.scrape_aavso.SVReduction', {'__all__': {'scrape_aavso_date_start': 2020-02-05 03:41:31.544401+00:00, 'scrape_aavso_date_end': 2020-02-05 03:44:27.154146+00:00, 'scrape_aavso_files': ['00200_cdec_wasp-12b_20160106__000442.zip', '00165_cdec_wasp-12b_20160106__022250.zip', '00170_cdec_wasp-12b_20160106__022250.zip', '00166_cdec_wasp-12b_20160108__022250.zip', '00216_fmaa_tres-3-b_20170502__093414.zip', '00209_fmaa_wasp-52-b_20171012__034435.zip', '00206_fmaa_wasp-52b_20171026__034132.zip', '00173_bsec_tres-3b_20171113__001532.zip', '00233_zrta_hat-p-32-b_20171220__050845.zip', '00171_ldia_qatar-1b_20181213__210747.zip', '00242_fmaa_hat-p-32-b_20181214__062005.zip', '00227_cgia_kelt-7b_20190115__191728.zip', '00174_ldia_hat-p-32-b_20190203__205603.zip', '00175_ldia_hat-p-36-b_20190223__223628.zip', '00178_lpac_kelt-3b_20190330__064144.zip', '00177_lpac_kps-1b_20190401__065610.zip', '00179_mhsb_hat-p-36_20190402__022548.zip', '00176_lpac_wasp-104b_20190402__071358.zip', '00187_lpac_k2-137b_20190411__061816.zip', '00180_mhsb_wasp-43b_20190418__023108.zip', '00181_akv_hat-p-36b_20190419__073456.zip', '00183_lpac_k2-137b_20190423__065125.zip', '00182_lpac_xo-1b_20190424__092856.zip', '00184_lpac_xo-6b_20190504__061718.zip', '00185_rdja_wasp-19b_20190517__100613.zip', '00246_dks_tres-3_20190518__055203.zip', '00186_lpac_wts-2b_20190518__081442.zip', '00189_rdja_hats-24b_20190527__125904.zip', '00188_lpac_kepler-1086b_20190530__075809.zip', '00193_mxi_qatar-1b_20190531__211012.zip', '00194_pcc_qatar-1b_20190531__223420.zip', '00190_lpac_kepler-446c_20190609__090103.zip', '00191_lpac_kepler-718b_20190611__073256.zip', '00192_pcc_wasp-48b_20190626__231029.zip', '00197_mxi_tres-3b_20190629__001259.zip', '00195_pcc_corot-2b_20190701__230856.zip', '00196_pcc_kelt-16_20190713__231822.zip', '00198_pcc_tres-2b_20190716__231356.zip', '00199_pcc_tres3b_20190719__222336.zip', '00201_pcc_hat-p-41b_20190720__231831.zip', '00207_pcc_wasp-92b_20190721__230837.zip', '00208_lpac_wasp-67b_20190808__065936.zip', '00214_mnic_xo-6-b_20190812__215454.zip', '00217_mnic_qatar-4-b_20190821__214704.zip', '00221_fmaa_wasp-10-b_20190826__050131.zip', '00218_mnic_tres-5-b_20190827__231322.zip', '00220_mnic_kepler-412-b_20190828__212333.zip', '00234_lpac_wts2b_20190901__064656.zip', '00222_pcc_wasp-3b_20190904__220652.zip', '00223_mnic_tres-2-b_20190906__204859.zip', '00224_mnic_tres-3-b_20190908__204627.zip', '00226_lpac_hd-189733-b_20190912__061611.zip', '00240_fmaa_hat-p-32-b_20190913__074756.zip', '00225_mnic_wasp-10-b_20190916__202510.zip', '00228_fmaa_hat-p-32-b_20190928__084711.zip', '00229_fmaa_wasp-10-b_20191002__073501.zip', '00230_mnic_tres-5-b_20191021__193302.zip', '00238_fmaa_hat-p-32-b_20191024__040421.zip', '00235_mnic_k2-30-b_20191105__210806.zip', '00245_dks_wasp-12_20191129__075051.zip', '00244_kgab_hat-p-19_20191202__041602.zip', '00247_fmaa_wasp-77-a-b_20200107__051300.zip', '00248_kadb_wasp-34-b_20200126__014328.zip'], 'ingest_headers': [], 'ingest_data': [], 'STATUS': [False, True]}})

**Comment by jpl-jengelke** [comment]
Reopened because it appears the aspects __iter__ is different between Shelf and Postgres.

**Comment by al-niessner** [comment]
Reopening this ticket is not required. This is actually ticket #32 and should be fixed in conjunction with #103. I thought I had them different and that disturbed me. Thanks for the output though as that will let me arrange them the same.

**Comment by jpl-jengelke** [comment]
Thanks Al.
