### ISSUE TITLE
review and repair dawgie.pl.LogDeferredException

### ISSUE THREAD

**Issue by al-niessner** [al-niessner/DAWGIE#111]
Seems like using the object as is is very dangerous. Need to review it in more detail and potentially effect repair.

**Comment by jpl-jengelke** [comment]
Should I hold off on deploying this for testing?

**Comment by al-niessner** [comment]
Not at all. I just need to review that object as it changed a bit from
1.2.x to 1.3.x and looks like I made it so anyone can get some really
confusing errors. Just seems like I should clean that up before 1.3 is
released. Doubt anything will need to change.
