### ISSUE TITLE
improve error messaging

### ISSUE THREAD

**Issue by al-niessner** [al-niessner/DAWGIE#124]
When there is a revision difference between the worker and server, the warning message should provide both.

**Comment by jpl-jengelke** [comment]
So I installed 1.2.12-rc01 and I am seeing the ValueError at the CLI, but not in the logs. Should I change logging levels? When the VE pops up the other instances just die, and nothing happens. It has blocked the scheduler.

**Comment by al-niessner** [comment]
Log level needs to be warning to see them. However, if they are not in the log but on the terminal window of the worker then the worker is not connected to the server at the time of the error.

**Comment by jpl-jengelke** [comment]
It should be at WARN right now. We can attach to the running instances with `cd /proj/survey-ws/ets-runtime/ ; docker-compose -f /proj/survey-ws/source/ets/server.yml logs --follow ops_worker`.

**Comment by jpl-jengelke** [comment]
Alternately, they can be viewed with a root account at /var/lib/docker/containers/<container-id>/<container-id>-json.log .

**Comment by jpl-jengelke** [comment]
Here’s a command to view all at the same time:
`cmdsettings="-i " ; for f in $(find /var/lib/docker/containers/ -type f -name "*-json.log") ; do bn=$( basename ${f} ) ; cmdsettings="${cmdsettings}${f} --label ${bn:0:11}- -I " ; done ; multitail ${cmdsettings::-4} ;`

Here’s a command to display all in their own windows:
`cmdsettings="" ; for f in $(find /var/lib/docker/containers/ -type f -name "*-json.log") ; do cmdsettings="${cmdsettings} -i ${f}" ; done ; multitail ${cmdsettings} ;`

**Comment by jpl-jengelke** [comment]
It should be at WARN right now. We can attach to the running instances with `cd /proj/survey-ws/ets-runtime/ ; docker-compose -f /proj/survey-ws/source/ets/server.yml logs --follow ops_worker`.

**Comment by jpl-jengelke** [comment]
Alternately, they can be viewed with a root account at `/var/lib/docker/containers/<container-id>/<container-id>-json.log`

**Comment by jpl-jengelke** [comment]
Here’s a command to view all at the same time:
`cmdsettings="-i " ; for f in $(find /var/lib/docker/containers/ -type f -name "*-json.log") ; do bn=$( basename ${f} ) ; cmdsettings="${cmdsettings}${f} --label ${bn:0:11}- -I " ; done ; multitail ${cmdsettings::-4} ;`

Here’s a command to display all in their own windows:
`cmdsettings="" ; for f in $(find /var/lib/docker/containers/ -type f -name "*-json.log") ; do cmdsettings="${cmdsettings} -i ${f}" ; done ; multitail ${cmdsettings} ;`
