### ISSUE TITLE
Test script using non-cross-platform commands

### ISSUE THREAD

**Issue by jpl-jengelke** [al-niessner/DAWGIE#15]
In `.ci/exercise_01.sh`, the continuous integration scripting uses 'mktemp -d' which creates directory trees deep inside local user home locations on Macs, not '`tmp`' as expected. This requires mounting user-specific directories in Docker that may contain sensitive and critical information. A workaround is a standardized temporary directory process. 

This request is to modify the above script (and any scripts with similar tooling) as follows (approximately lines 47-53): 
```
if current_state
then
    tempdir=$(mktemp -d)
    mkdir -p ${tempdir}/{db,dbs,fe,gnupg,logs,stg}
    mkdir ${tempdir}/gnupg/private-keys-v1.d
    chmod 700 ${tempdir}/gnupg ${tempdir}/gnupg/private-keys-v1.d
    GNUPGHOME=${tempdir}/gnupg gpg2 --batch --generate-key <<EOF 
```
... with some variant of the following ...
```
# cross-platform: 
#     docker must share /tmp 

## ensure command for md5summing is available
## IFF md5sum is aliased wipe it out (Mac compatibility)
type -t md5sum | grep -qi "alias" && unalias md5sum >/dev/null 2>&1 
## if md5sum DNE create alias or exit (Mac compatibility)
which md5sum >/dev/null 2>&1 || which md5 >/dev/null 2>&1 && alias md5sum='md5 -r' || 
    { echo "ERROR: MD5SUM command not found!" && exit 127 ; }
## ensure aliases are available in subshells
shopt -s expand_aliases

# create a hash to be used for temp dir  
tempHash="$( cut -c1-8 <( date "+%S%N" | md5sum ))" 
tempRoot="/tmp/dawgie"
mkdir -p "${tempRoot}"

if current_state
then
    tempdir="${tempRoot}/tmp.${tempHash}"
    echo "**********    USING TEMP DIR at ${tempdir}    **********" 
    mkdir -p ${tempdir}/{db,dbs,fe,gnupg,logs,stg}
    mkdir ${tempdir}/gnupg/private-keys-v1.d
    chmod 700 ${tempdir}/gnupg ${tempdir}/gnupg/private-keys-v1.d
# mark GPG sockets as fifo 
    mkfifo -m 700 ${tempdir}/gnupg/S.gpg-agent.extra ${tempdir}/gnupg/S.gpg-agent.ssh \
        ${tempdir}/gnupg/S.gpg-agent ${tempdir}/gnupg/S.gpg-agent.browser
    export GPG_TTY=/dev/tty
    GNUPGHOME=${tempdir}/gnupg gpg2 --batch --generate-key <<EOF
```
Feel free to contact me for more info or to let me know if this is a palatable change or not.

**Comment by al-niessner** [comment]
A cleaner [fix](https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x) would be to make mktemp compatible with macOS. It would look more like:

`tempdir=$(mktemp -d 2>/dev/null || mktemp -d -t tmp)`

This should do the right thing on Linux first then the MAC if the first fail. For more details about why and how it works, see the 'fix' link at the start of this comment.

**Comment by al-niessner** [comment]
In the end, it may be better to record the changes in the script for a MAC rather than make the script platform independent. The scripts intent is as a cheat sheet and used prior to deployment to show dawgie still works with toy examples. In the first case, as a cheat sheet, the cross platform changes just make it harder to understand what is important for dawgie vs what is important for a specific platform. In the second case, automated checks, it is always run on a linux platform.

**Comment by jpl-jengelke** [comment]
```
john-engelke-2:ets johnengelke$ mktemp -d
/var/folders/0_/0mssd1656q78c47k0_yk7sn00000gp/T/tmp.WDr3CTdU
john-engelke-2:ets johnengelke$ mktemp -d -t 'tmp'
/var/folders/0_/0mssd1656q78c47k0_yk7sn00000gp/T/tmp.mESVCa7T
john-engelke-2:ets johnengelke$ mktemp -d -t 'tmpcustom'
/var/folders/0_/0mssd1656q78c47k0_yk7sn00000gp/T/tmpcustom.zTpY2Hld
john-engelke-2:ets johnengelke$ mktemp -d -t 'tmpcustom' /tmp/tmpp.XXXXXX
/var/folders/0_/0mssd1656q78c47k0_yk7sn00000gp/T/tmpcustom.IuRbRwLO
/tmp/tmpp.yxMn3y
john-engelke-2:ets johnengelke$ mktemp -d -t 'tmpcustom' /tmp/tmpp.XXXXXXXXXXXX
/var/folders/0_/0mssd1656q78c47k0_yk7sn00000gp/T/tmpcustom.0XQ2t6hD
/tmp/tmpp.RFJI7nfYQDLV
john-engelke-2:ets johnengelke$ 
```

**Comment by jpl-jengelke** [comment]
The Mac uses what is likely an older version of `mktemp` which imposes its own templating requirements for the directory location. It ignores the `p`-flag to specify directory root. The older version still takes a template, which can be provided at the end of the command. So I think something like this will work (based on the info provided in your earlier post). ... 
`mkdir -d /tmp/tmp.XXXXXX` will work on both platforms. That's a minor change that should not impact the script.

**Comment by jpl-jengelke** [comment]
Resolved. Also added verification of gpg2 and fall back to gpg. Also fixed minor conditional test glitch for numeric comparison.
