### ISSUE TITLE
log display lost

### ISSUE THREAD

**Issue by al-niessner** [al-niessner/DAWGIE#31]
The log display on the front page and logs page are empty. Using a curl to /app/pl/log returns a JSON object. Probably means it is in the display portion.

**Comment by jllamas** [comment]
Can you please send me a sample of  ` curl to /app/pl/log` so I can test with different data.

**Comment by al-niessner** [comment]
There is a quoting problem with Python's json module. More specifically, there is a problem in my use of the Python's json module and double quotes in the string are not being made friendly to json.dumps() which causes them to look like bad JSON. Hence, the front end cannot display them.

For instance the python string:

`Could not find the state vector "foo" withing algorithm "bar" for task "snafu".`

is being serialized by json.dumps() to:

`"Could not find the state vector "foo" withing algorithm "bar" for task "snafu"."`

Using jsonlint.com, it clearly is wrong.

**Comment by al-niessner** [comment]
This test:

```
import json

s = json.dumps ([{'test':'embedded string "here are the quotes" to test problem "being seen"'}])
print (s)
d = json.loads (s)
print (d)
```

produces this output:

```
[{"test": "embedded string \"here are the quotes\" to test problem \"being seen\""}]
[{'test': 'embedded string "here are the quotes" to test problem "being seen"'}]
```

Leading to the question of why is json.dumps() putting in \ in this instance but not in the pipeline?

**Comment by al-niessner** [comment]
Nope. Actually it is dawgie.pl.logger.fe that seems to be the problem. It is building the json object using logging.formatter. Need to rethink that one.
