### ISSUE TITLE
db result filter failure

### ISSUE THREAD

**Issue by al-niessner** [al-niessner/DAWGIE#36]
Attached are two images. The image below is searching for a specific target in user mode and finding a small number of state vectors. Most important is the highlighted state vector that a single identified run ID of 105.
![target](https://user-images.githubusercontent.com/1130658/63198735-7c6d1e80-c030-11e9-9fe4-b4e25d298891.png)

Changed the search to locate that state vector in user mode. The image below is the result which is empty. Switching to dev mode shows all targets with many run IDs each but not shown here.
![sv](https://user-images.githubusercontent.com/1130658/63198734-7c6d1e80-c030-11e9-9c0d-37638c96eafd.png)

It works as expected when searching targets but not as expected for state vectors.

**Comment by jllamas** [comment]
Excellent, thanks for breaking it down, I'll take a look at this next week.

**Comment by al-niessner** [comment]
Closed by #38
