### ISSUE TITLE
Off-lab scripts pulled into DAWGIE front end

### ISSUE THREAD

**Issue by jpl-jengelke** [al-niessner/DAWGIE#62]
Not sure if this is a concern or not but off-Lab scripts are being used for the presentation layer in DAWGIE. For instance, in the representation of the State Vectors, the following scripts are pulled from [https://pydata.org/](https://pydata.org/) : 
`<script src="https://cdn.pydata.org/bokeh/release/bokeh-1.4.0.min.js"></script><script src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.4.0.min.js"></script><script src="https://cdn.pydata.org/bokeh/release/bokeh-tables-1.4.0.min.js"></script>`

These could be hosted locally or moved into the application for retrieval from file which would isolate them from any external changes, both erroneous or malicious.

**Comment by al-niessner** [comment]
These are fine. [bokeh](https://docs.bokeh.org/en/latest/index.html) is the plotting engine chosen for displaying state vectors. Getting them from pydata.org/bokeh is a minor, at best, security risk.
