### ISSUE TITLE
Missing log messages for Run IDs

### ISSUE THREAD

**Issue by jpl-jengelke** [al-niessner/DAWGIE#63]
Log messages appear to have either changed or to be missing from DAWGIE 1.2.7 for events triggered beyond the initial item in a dependency tree. The following show up and then no more appear until the run ID itself increments from (1) to (2). Some behavior is odd because I also noticed that the run ID (2) appeared in an analysis in the middle of the dependency tree when the app was relaunched but the analysis had not run. More pointedly, the alert seemed to only show up in the middle of the dependency tree if the run ID incremented then.  

`2019-11-11 10:04:29,261 :: dawgie.pl.farm :: CRITICAL :: New run ID (1) for algorithm <some_analysis_1> trigger by the event: New software changeset <some_hash_1>
2019-11-11 10:04:29,264 :: dawgie.pl.farm :: CRITICAL :: New run ID (1) for algorithm <some_analysis_2> trigger by the event: New software changeset <some_hash_2>
...
<no more>
...`

My question is did the behavior change to only log this at run ID changes or should it appear for the first items i9n a dependency tree or should it just appear all the time. Previously it appeared all the time which helped to note that a run was triggered.

**Comment by al-niessner** [comment]
This is the correct operation. You should get one message per commit. The abundant messages from before was from a coding error fixed in #55
