### ISSUE TITLE
In templating engine, HTML closing tags are doubly assigned attributes

### ISSUE THREAD

**Issue by jpl-jengelke** [al-niessner/DAWGIE#75]
Two issues in the DAWGIE templating engine (dawgie.de.html.py): 

1. When a style is assigned, both opening and closing tags receive the style, rendering malformed browser content. 
Example: 
`<p style="color: blue;"></p style="color: blue;">`
2. Void elements are assigned closing tags.
Example:
`<hr></hr>`

[List of html void elements](https://www.w3.org/TR/html52/single-page.html#void-elements)
Also, https://html.spec.whatwg.org/ , see `void elements`.

**Comment by jpl-jengelke** [comment]
I would *really* like to get this into 1.2.8, if possible. I'll try to complete the code tonight.

**Comment by al-niessner** [comment]
The void element list is small so feel free to add it. No rush as there is not immediate need to release 1.2.8.

**Comment by jpl-jengelke** [comment]
I've expanded the scope of this slightly but it will only modify the html.py file.

- Add default STYLE spec to match master application
- Add class tag
- Add PRE tag

I was working on the rendering to render primitives inline with declarations but it turns out to be too much of a change, so it can be modified later, as desired.

**Comment by al-niessner** [comment]
Remember it has to work with PDF and Lyx as well.

**Comment by jpl-jengelke** [comment]
I may need help testing that. The changes should not be so substantial that they will break either PDF or Latex, I believe.

**Comment by jpl-jengelke** [comment]
I will make the pull request to the 1.2.9 branch. Thanks.

**Comment by al-niessner** [comment]
You can make it part of 1.3.0 if you prefer. Just letting you know about
the branch to make you aware of the choice you have.

**Comment by jpl-jengelke** [comment]
Should I make the PR to both branches? In other words, if it gets into 1.2.9 will it be in 1.3.0 eventually?

**Comment by al-niessner** [comment]
No. I recommend master (1.3 release) as there are some pretty scoping
changes in it that could make it a merge nightmare from 1.2 to 1.3. That is
the clue that if you merge it in 1.2 branch, then it has to be merge to
master at some point in time too from the 1.2 branch.

**Comment by jpl-jengelke** [comment]
I opted for additional changes to include scrubbing input values of potentially malicious code: "Standardized templating on f-strings, added clean methods to limit malicious code, standardized class, id and style attributes, rearranged order to support writing customizations after file loads for script and css imports, remove superfluous variables added to init, separated legacy and new functions to support backwards compatibility."

**Comment by jpl-jengelke** [comment]
Changes complete for now. Pull requests have been created for the following branches: 
- issue_75 (to master)
- issue_75-1.2.x (to Release-1.2.x)
