### ISSUE TITLE
move to https

### ISSUE THREAD

**Issue by al-niessner** [al-niessner/DAWGIE#76]
Seems that https is becoming a requirement. Look at how to serve as https.

**Comment by jpl-jengelke** [comment]
Could it be done by fronting the server with Apache and running mod_rewrite? Then the server can be hosted on port 81 and the actual port obscured locally. With iptables setup correctly, no one could access the Docker instance except on the localhost. It seems to me this could be handled by sysadmins without complicating development with setting up local, self-signed certs that would require browser users to add them to the local store, anyway.

**Comment by jpl-jengelke** [comment]
Also, this could definitely be impactful to access capabilities. Would it be possible to push this to 1.2.9 and maybe do that standalone in there so as not to impact any of today's features?

**Comment by jpl-jengelke** [comment]
I found these ... Just wanted to leave them here ... 
https://twistedmatrix.com/documents/current/core/howto/ssl.html 
https://letsencrypt.org/ -- OSS, free certs accepted in modern browsers

**Comment by al-niessner** [comment]
> Could it be done by fronting the server with Apache and running mod_rewrite? Then the server can be hosted on port 81 and the actual port obscured locally. With iptables setup correctly, no one could access the Docker instance except on the localhost. It seems to me this could be handled by sysadmins without complicating development with setting up local, self-signed certs that would require browser users to add them to the local store, anyway.

Not interested in apache. This is a control web service not a meant as a full blown web page server. While it has taken on a bit of that latter role, it is still quite minimal and the desire is to keep it that way.

**Comment by al-niessner** [comment]
After reviewing the work required, it does seem to be more of a new feature than an bug fix.
