### ISSUE TITLE
Running tasks not marked Running during processing

### ISSUE THREAD

**Issue by jpl-jengelke** [al-niessner/DAWGIE#97]
In DAWGIE 1.2.9-RC1, processing was taking place in an ETS algorithm. However, the algorithm continued to read "Queued" while it was generating files. It appeared to jump from "Queued" to "Complete". See attached image.
<img width="1680" alt="Screen Shot 2020-01-13 at 6 53 18 PM" src="https://user-images.githubusercontent.com/52300928/72310451-a99d1780-3636-11ea-8842-bd854b382fa7.png">

**Comment by al-niessner** [comment]
I am not sure if it is meant to show all of the states. It probably should and this should be counted as a bug. While a bug, its priority should be considered low.

**Comment by jpl-jengelke** [comment]
I'm closing this for now with the option of reopening it. I believe it may be related to pending UI updates on the ETS side.
